// Catálogo comercial de módulos de expansión: nombre, precio de referencia (texto), nivel sugerido y qué tan real es cada uno.
// Vivía dentro de superadmin/paquetes/page.tsx; ahora lo leen Cobros → Precios (catálogo y matriz de planes).
// Los precios reales se editan en Cobros → Precios; el texto `price` de aquí es solo la referencia de partida.

export interface StoreModule {
  id: string;
  name: string;
  icon: string;
  price: string;
  description: string;
  active: boolean;
  // Desde qué plan de Paquetes conviene ofrecerlo — sugerencia editorial, no
  // gatea nada todavía (Paquetes sigue con sus features sueltas, sin leer
  // esto). Sirve para ordenar la matriz visual de abajo.
  tier: 'Basic' | 'Pro' | 'Enterprise';
  // Qué tan real es hoy en el código, no en la idea. 'parcial' = ya existe
  // algo funcionando por debajo (aunque no esté conectado al toggle de acá);
  // 'no_construido' = es puro catálogo comercial, cero código todavía.
  buildStatus: 'parcial' | 'no_construido';
  buildNote: string;
}

export const NO_CODE_YET = 'Todavía no tiene código — es puro catálogo comercial por ahora.';

export const INITIAL_MODULES: StoreModule[] = [
  {
    id: 'dominio-propio',
    name: 'Dominio Propio Personalizado (.com / .pe)',
    icon: 'language',
    price: 'S/ 49 /mes',
    description: 'La tienda abre con su propia dirección web (ej. mitienda.pe o tunegocio.com) con certificado de seguridad SSL incluido. El cliente lo compra en su registrador y Boga lo conecta.',
    active: true,
    tier: 'Pro',
    buildStatus: 'parcial',
    buildNote: 'Construido y activo: proxy de Next.js resuelve dominios propios en memoria y reescribe transparentemente a la tienda.',
  },
  {
    id: 'loyverse-pos',
    name: 'Integración Loyverse POS',
    icon: 'sync_alt',
    price: 'S/ 49 /mes',
    description: 'Sincronización bidireccional automática de catálogo, precios y stock con el punto de venta Loyverse mediante webhooks en tiempo real.',
    active: true,
    tier: 'Pro',
    buildStatus: 'parcial',
    buildNote: 'Construido y funcionando: endpoint /api/loyverse/sync, webhooks /api/loyverse/webhook y descuento automático en ventas de Boga.',
  },
  {
    id: 'franquicias',
    name: 'Módulo de Franquicias',
    icon: 'account_tree',
    price: 'S/ 299 /mes',
    description: 'El dueño ve cuánto vende cada sede desde su celular: ranking entre locales y comparativas. Solo tiene sentido una vez que hay más de una sede.',
    active: true,
    tier: 'Enterprise',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'facturacion-electronica',
    name: 'Facturación Electrónica SUNAT',
    icon: 'receipt_long',
    price: 'S/ 0.15 /boleta',
    description: 'Emisión de boletas y facturas electrónicas directo a SUNAT por cada venta procesada en el sistema. Se cobra por boleta enviada, no por mes.',
    active: true,
    tier: 'Pro',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'business-intelligence',
    name: 'Business Intelligence',
    icon: 'insights',
    price: 'S/ 199 /mes',
    description: 'Predicción de demanda: qué días y en qué sedes conviene contratar más personal, según el historial de ventas.',
    active: false,
    tier: 'Enterprise',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'inventario-inteligente',
    name: 'Inventario Inteligente',
    icon: 'inventory',
    price: 'S/ 149 /mes',
    description: 'No solo dice "hay 10 pollos": avisa "según tus ventas de los últimos 3 viernes, mañana te quedas sin papas a las 8pm — compra más ahora". Alerta predictiva por insumo, no solo conteo de stock.',
    active: false,
    tier: 'Pro',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'repartidores-propios',
    name: 'Repartidores Propios',
    icon: 'moped',
    price: 'S/ 249 /mes',
    description: 'App mini para que los motorizados del local vean su ruta y marquen "entregado", con mapa en tiempo real para el cliente — un Uber Eats propio del negocio, sin comisión a terceros.',
    active: false,
    tier: 'Enterprise',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'marketing-automatizado',
    name: 'Marketing Automatizado',
    icon: 'campaign',
    price: 'S/ 129 /mes',
    description: 'Correos y SMS automáticos por fecha o comportamiento: "Feliz cumpleaños Juan, hoy tu cuarto de pollo es gratis" o reactivación de clientes que no piden hace semanas.',
    active: false,
    tier: 'Pro',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'presencia-marketplace',
    name: 'Presencia en el Marketplace BogaHub',
    icon: 'storefront',
    price: 'S/ 99 /mes',
    description: 'Aparecer también en el marketplace compartido de BogaHub (búsqueda y categorías cruzadas entre tiendas), no solo en la tienda propia del negocio. Más alcance, pero comparte vidriera con otros comercios.',
    active: true,
    tier: 'Basic',
    buildStatus: 'parcial',
    buildNote: 'El listado de /market ya muestra todas las tiendas — falta el flag is_public para que activar/desactivar esto cambie algo de verdad.',
  },
  {
    id: 'notificaciones-inteligentes',
    name: 'Notificaciones Inteligentes ("Vecino Cercano")',
    icon: 'notifications_active',
    price: 'S/ 179 /mes',
    description: 'Geofencing: si el cliente pasa a 300m del local, le llega "estás a 2 minutos, ven ahora y te regalamos el café". Es lo mismo que hace Starbucks y les sale carísimo — acá viene incluido. Gamificación: "te faltan 2 pedidos para ser Cliente Oro" — el cliente abre la app solo, sin invadir por WhatsApp.',
    active: false,
    tier: 'Pro',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'lealtad-digital',
    name: 'Sistema de Lealtad Digital ("Socio Fiel")',
    icon: 'military_tech',
    price: 'S/ 99 /mes',
    description: 'La tarjeta de cartón que sellan y se pierde, digital y sin que se pierda nunca: compra 5 y el 6to gratis, o 1 sol = 1 punto canjeable por extras. Niveles Bronce/Plata/Oro según cuánto vuelve. El valor real para el dueño: "Juan ya tiene 4 sellos, mandale una notificación ahora para que venga hoy por el 5to" — reactivación con nombre y apellido, no un descuento genérico.',
    active: false,
    tier: 'Basic',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'racha-envio-gratis',
    name: 'Racha de Envío Gratis',
    icon: 'local_fire_department',
    price: 'S/ 89 /mes',
    description: 'Mientras el cliente mantenga su racha de pedidos (ej. 1 por semana) tiene envío gratis. Si la corta, la pierde y tiene que reconstruirla desde cero — el mismo gancho que hace que nadie quiera perder su racha en Duolingo.',
    active: false,
    tier: 'Basic',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'app-nativa',
    name: 'App Nativa (Play Store / App Store)',
    icon: 'apps',
    price: 'S/ 1,500 pago único + S/ 79 /mes',
    description: 'Va más allá del PWA (que ya es gratis para todos): empaqueta la tienda como app real, publicada en Google Play y App Store con su propio ícono y ficha. El mantenimiento mensual cubre las actualizaciones que piden ambas tiendas cada tanto.',
    active: false,
    tier: 'Enterprise',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'pasarela-pago-propia',
    name: 'Pasarela de Pago Propia',
    icon: 'credit_card',
    price: 'S/ 0.30 /transacción',
    description: 'Checkout con tarjeta o Yape dentro de la misma app (Izipay) en vez de derivar todo a WhatsApp para coordinar el pago. El comercio conecta su propia cuenta Izipay: el dinero va directo a él.',
    active: false,
    tier: 'Pro',
    buildStatus: 'parcial',
    buildNote: 'Construido: carrito con «Pagar con tarjeta o Yape» (plantillas con el carrito compartido), página de pago, confirmación firmada e IPN, pedido «Pagado» y claves cifradas. Falta probarlo con una cuenta Izipay real y sumarlo a las plantillas con carrito propio (Mirka, Amazonia, Mercado…). Se activa por tienda con el módulo «Cobro online (Izipay)».',
  },
  {
    id: 'reservas-citas',
    name: 'Reservas y Citas',
    icon: 'calendar_month',
    price: 'S/ 129 /mes',
    description: 'Calendario de turnos con hora fija en vez de solo catálogo de productos — pensado para salones, clínicas y servicios con cita previa.',
    active: false,
    tier: 'Pro',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'programa-referidos',
    name: 'Programa de Referidos',
    icon: 'group_add',
    price: 'S/ 89 /mes',
    description: '"Invita a un amigo y ambos ganan": código de referido con recompensa automática tanto para quien invita como para el invitado en su primer pedido.',
    active: false,
    tier: 'Basic',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'marca-blanca-total',
    name: 'Marca 100% Blanca',
    icon: 'visibility_off',
    price: 'S/ 149 /mes',
    description: 'Saca cualquier rastro de "Powered by BogaHub" de la tienda — para el comercio que no quiere que se note qué tecnología usa por debajo.',
    active: false,
    tier: 'Enterprise',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'resenas-reales',
    name: 'Reseñas Reales de Clientes',
    icon: 'rate_review',
    price: 'S/ 79 /mes',
    description: 'Hoy el rating de cada tienda lo carga el comercio a mano en el panel — no sale de compras reales. Este módulo pide reseña al cliente después de cada pedido y calcula el promedio solo, con historial de comentarios.',
    active: false,
    tier: 'Basic',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'analitica-favoritos',
    name: 'Analítica de Favoritos',
    icon: 'favorite',
    price: 'S/ 119 /mes',
    description: 'Los "Me Gusta" del cliente hoy quedan solo en el celular de quien los guardó — el dueño nunca se entera. Este módulo los sincroniza y le muestra qué productos guarda la gente pero no compra: la señal de remarketing más barata que existe.',
    active: false,
    tier: 'Pro',
    buildStatus: 'parcial',
    buildNote: 'Los favoritos ya existen (guardados en el celular del cliente, ver app/orders/page.tsx) — falta sincronizarlos a Supabase para que el dueño los vea.',
  },
  {
    id: 'auto-branding-ia',
    name: 'Auto-Branding con IA',
    icon: 'auto_awesome',
    price: 'S/ 59 /mes',
    description: 'La extracción de colores de logo que hoy solo usas vos desde superadmin, self-service para el dueño: sube su logo o una foto de un plato y la tienda se retematiza sola, sin tener que pedírtelo.',
    active: false,
    tier: 'Basic',
    buildStatus: 'parcial',
    buildNote: 'El motor ya existe y funciona (lib/extractThemeClient.ts) — hoy solo lo usa superadmin, falta exponérselo al dueño.',
  },
  {
    id: 'delivery-zonas-dinamico',
    name: 'Delivery por Zonas con Tarifa Dinámica',
    icon: 'pin_drop',
    price: 'S/ 99 /mes',
    description: 'La "zona" de cada tienda hoy es un texto decorativo. Este módulo la convierte en zonas reales de reparto, cada una con su propio costo de envío y tiempo estimado — en vez de un dato suelto que no cobra nada.',
    active: false,
    tier: 'Pro',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'happy-hour-automatico',
    name: 'Happy Hour Automático',
    icon: 'bolt',
    price: 'S/ 139 /mes',
    description: 'Detecta las horas muertas del local (ej. martes 3-5pm) y lanza sola un 2x1 o descuento por los próximos 60 minutos. Liquida stock que se iba a malograr y llena el local en horarios flojos, sin que el dueño tenga que acordarse de activarlo.',
    active: false,
    tier: 'Pro',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'suscripcion-vip',
    name: 'Suscripción VIP (estilo Amazon Prime)',
    icon: 'workspace_premium',
    price: 'S/ 199 /mes + 5% de lo cobrado en suscripciones',
    description: 'El cliente le paga al comercio, por ejemplo S/ 20/mes, y a cambio tiene delivery gratis siempre + 10% de descuento fijo. El dueño gana ingreso asegurado todos los meses aunque el cliente no compre; vos ganás una comisión por administrar esa suscripción dentro de tu plataforma.',
    active: false,
    tier: 'Enterprise',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'reserva-y-pide',
    name: 'Reserva y Pide (Pre-order)',
    icon: 'restaurant_menu',
    price: 'S/ 129 /mes',
    description: '"Llego en 15 minutos, quiero mi pedido servido apenas me siente". El cliente paga desde la app, la cocina recibe la orden al toque, y cuando llega la comida ya está lista — cero colas, cero espera.',
    active: false,
    tier: 'Pro',
    buildStatus: 'no_construido',
    buildNote: NO_CODE_YET,
  },
  {
    id: 'sitio-web-propio',
    name: 'Página Web / Sitio Propio',
    icon: 'language',
    price: 'Desde S/ 199 pago único + S/ 39 /mes',
    description: 'Landing page o catálogo con dominio propio, fuera del ecosistema BogaHub — para SEO y para compartir un link "serio" en redes. El esfuerzo no es el mismo para todos los rubros: una carta de restaurante con pocos platos es mucho más simple que un catálogo de ecommerce con cientos de productos, así que el precio final se cotiza según cuánto tiene la tienda.',
    active: false,
    tier: 'Pro',
    buildStatus: 'parcial',
    buildNote: 'Cada tienda ya tiene su link propio (/slug) que cumple parte de esto — falta el dominio 100% propio y la ficha SEO dedicada.',
  },
];
