export interface StoreTheme {
  primary: string;
  onPrimary: string;
  primaryContainer: string;
  secondary: string;
  secondaryContainer: string;
  background: string;
  surface: string;
  surfaceContainer: string;
  surfaceContainerLow: string;
  surfaceContainerLowest: string;
  surfaceContainerHigh: string;
  onBackground: string;
  onSurface: string;
  onSurfaceVariant: string;
  outlineVariant: string;
  fontHeadline: string;
  fontBody: string;
  fontLabel: string;
}

export interface DemoProduct {
  name: string;
  price: number;
  category: string;
  subcategory?: string;
  image: string;
  description?: string;
  /** Medidas con su precio (100 g / 250 g / 1 kg…). `price` es la más barata. Ver lib/presentaciones.ts. */
  presentaciones?: { label: string; price: number }[];
  /** Solo para la demo: así se ven los combos y las ofertas de la plantilla. */
  esCombo?: boolean;
  /** Solo para la demo: precio normal tachado (oferta). */
  priceAnterior?: number;
  /** Solo para la demo: es un servicio (se reserva, no va al carrito). En `subcategory` va cuánto dura ("45 min"). */
  esServicio?: boolean;
}

export interface TemplateConfig {
  id: string;
  name: string;
  category: string;
  theme: StoreTheme;
  heroImage: string;
  heroAlt: string;
  iconImage?: string;
  categories: { name: string; icon: string; href: string }[];
  demoProducts: DemoProduct[];
  /** Solo para el preview de la plantilla (/preview/:id): asi la demo no se ve vacia. Cada tienda real carga los suyos, o los deja vacios. */
  zona?: string;
  direccion?: string;
  horario?: string;
  rating?: number;
  whatsapp?: string;
}

const TEMPLATES: Record<string, TemplateConfig> = {
  default: {
    id: 'default',
    name: 'Default Minimal',
    category: 'Negocios',
    heroImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=1200&q=80',
    heroAlt: 'minimalist business storefront',
    theme: {
      primary: '#0058be',
      onPrimary: '#ffffff',
      primaryContainer: '#2170e4',
      secondary: '#545f73',
      secondaryContainer: '#d5e0f8',
      background: '#f9f9ff',
      surface: '#ffffff',
      surfaceContainer: '#ecedf7',
      surfaceContainerLow: '#f2f3fd',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#e6e7f2',
      onBackground: '#191b23',
      onSurface: '#191b23',
      onSurfaceVariant: '#424754',
      outlineVariant: '#c2c6d6',
      fontHeadline: "'Outfit', sans-serif",
      fontBody: "'Outfit', sans-serif",
      fontLabel: "'Outfit', sans-serif",
    },
    categories: [],
    demoProducts: [
      { name: 'Producto Ejemplo', price: 25.00, category: 'General', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80', description: 'Descripción del producto' },
      { name: 'Servicio Premium', price: 50.00, category: 'General', image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&q=80', description: 'Servicio profesional de alta calidad' },
    ],
  },

  sunset: {
    id: 'sunset',
    name: 'Sunset Dark',
    category: 'Gourmet',
    heroImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBHmeiaOsTXv2-kWJBCWi9uFd37xlyoGDpux03IogklXq1QxJFIOqy45sOanh9a3GdXv0m0yRNtTOyLQwkBZNlFYd_y4eVOvViwD1pK4QFZXmJomFCUqGECObJ1Ix4Tdq9hGBTItdravESWy1zWgq4lP8_HewhOD6dfZgTM4uX7I-FGbDFXXMW5YlaAVBPtzWyKQxm8L1T8SnJYQsAiPTbpU98meANSMRdWExpDhL8gueDCH_6C4_xX0TYuw8Y8CTjTT0MYAg6hEjpT',
    heroAlt: 'moody high-end cocktail bar at dusk with warm golden lighting',
    theme: {
      primary: '#f2ca50',
      onPrimary: '#3c2f00',
      primaryContainer: '#d4af37',
      secondary: '#ffb77d',
      secondaryContainer: '#fd8b00',
      background: '#131313',
      surface: '#131313',
      surfaceContainer: '#201f1f',
      surfaceContainerLow: '#1c1b1b',
      surfaceContainerLowest: '#0e0e0e',
      surfaceContainerHigh: '#2a2a2a',
      onBackground: '#e5e2e1',
      onSurface: '#e5e2e1',
      onSurfaceVariant: '#d0c5af',
      outlineVariant: '#4d4635',
      fontHeadline: "'Noto Serif', serif",
      fontBody: "'Manrope', sans-serif",
      fontLabel: "'Manrope', sans-serif",
    },
    categories: [
      { name: 'Cocina', icon: 'restaurant', href: 'kitchen' },
      { name: 'Bar', icon: 'local_bar', href: 'bar' },
      { name: 'Café', icon: 'coffee', href: 'cafe' },
    ],
    demoProducts: [
      { name: 'Ribeye Steak', price: 45.00, category: 'Cocina', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&q=80', description: 'Corte angus con guarnición' },
      { name: 'Mojito Clásico', price: 18.00, category: 'Bar', image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f1c2?w=400&q=80', description: 'Ron, hierbabuena, limón' },
      { name: 'Café Especial', price: 12.00, category: 'Café', image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&q=80', description: 'Café de especialidad filtrado' },
    ],
  },

  natura: {
    id: 'natura',
    name: 'Natura Organic',
    category: 'Salud y Bienestar',
    heroImage: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
    heroAlt: 'selva amazónica exuberante',
    theme: {
      primary: '#00a651',
      onPrimary: '#ffffff',
      primaryContainer: '#2D6A4F',
      secondary: '#1B4332',
      secondaryContainer: '#1B4332',
      background: '#F8F9FA',
      surface: '#ffffff',
      surfaceContainer: '#f0f4f0',
      surfaceContainerLow: '#f8faf8',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#e8ede8',
      onBackground: '#1A1A1A',
      onSurface: '#1A1A1A',
      onSurfaceVariant: '#444444',
      outlineVariant: '#d0d8d0',
      fontHeadline: "'Outfit', sans-serif",
      fontBody: "'Outfit', sans-serif",
      fontLabel: "'Outfit', sans-serif",
    },
    categories: [
      { name: 'Frutas', icon: 'nutrition', href: 'frutas' },
      { name: 'Verduras', icon: 'eco', href: 'verduras' },
      { name: 'Carnes', icon: 'set_meal', href: 'carnes' },
    ],
    demoProducts: [
      { name: 'Frutas del Día', price: 8.50, category: 'Frutas', image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&q=80', description: 'Selección de frutas frescas' },
      { name: 'Verduras Orgánicas', price: 12.00, category: 'Verduras', image: 'https://images.unsplash.com/photo-1557844352-761f2565b576?w=400&q=80', description: 'Pack de verduras de temporada' },
      { name: 'Carne de Res', price: 28.00, category: 'Carnes', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&q=80', description: 'Carne de res premium 1kg' },
    ],
  },

  amazonia: {
    id: 'amazonia',
    name: 'Amazonia Fresh',
    category: 'Mercado',
    heroImage: 'https://images.unsplash.com/photo-1590012314607-cda9d9b699ae?w=1200&q=80',
    heroAlt: 'productos artesanales de la selva profunda',
    theme: {
      primary: '#b25329',
      onPrimary: '#ffffff',
      primaryContainer: '#8f3d1b',
      secondary: '#5c3d2e',
      secondaryContainer: '#5c3d2e',
      background: '#faf7f2',
      surface: '#ffffff',
      surfaceContainer: '#f5ede2',
      surfaceContainerLow: '#faf7f2',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#ebddcb',
      onBackground: '#2c1e18',
      onSurface: '#2c1e18',
      onSurfaceVariant: '#66554d',
      outlineVariant: '#e6d7c5',
      fontHeadline: "'Outfit', sans-serif",
      fontBody: "'Outfit', sans-serif",
      fontLabel: "'Outfit', sans-serif",
    },
    categories: [
      { name: 'Artesanía', icon: 'interests', href: 'artesania' },
      { name: 'Bienestar', icon: 'spa', href: 'bienestar' },
      { name: 'Alimentos', icon: 'restaurant', href: 'alimentos' },
    ],
    demoProducts: [
      { name: 'Canasta Artesanal', price: 35.00, category: 'Artesanía', image: 'https://images.unsplash.com/photo-1590005354167-6da9783c12f4?w=400&q=80', description: 'Tejido a mano por artesanos locales' },
      { name: 'Aceite de Sacha Inchi', price: 22.00, category: 'Bienestar', image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&q=80', description: 'Aceite natural amazónico 250ml' },
      { name: 'Miel de Selva', price: 18.00, category: 'Alimentos', image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&q=80', description: 'Miel pura de abejas nativas' },
    ],
  },

  sweetkittynails: {
    id: 'sweetkittynails',
    name: 'Sweet Kitty Nails',
    category: 'Moda y Belleza',
    heroImage: 'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=1200&q=80',
    heroAlt: 'Sweet Kitty Nails premium pink glossy salon',
    theme: {
      primary: '#ff85a2',
      onPrimary: '#ffffff',
      primaryContainer: '#2c1015',
      secondary: '#ffccd5',
      secondaryContainer: '#fff0f3',
      background: '#fff5f6',
      surface: '#ffffff',
      surfaceContainer: '#ffe5ec',
      surfaceContainerLow: '#fff5f6',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#ffd3e8',
      onBackground: '#2c1015',
      onSurface: '#2c1015',
      onSurfaceVariant: '#7a5259',
      outlineVariant: '#ffccd5',
      fontHeadline: "'Outfit', sans-serif",
      fontBody: "'Outfit', sans-serif",
      fontLabel: "'Outfit', sans-serif",
    },
    categories: [
      { name: 'Manicura Gel', icon: 'dry_cleaning', href: 'manicura' },
      { name: 'Uñas Acrílicas', icon: 'brush', href: 'acrilicas' },
      { name: 'Nail Art 3D', icon: 'palette', href: 'nailart' },
      { name: 'Pedicura Spa', icon: 'spa', href: 'pedicura' },
    ],
    demoProducts: [
      { name: 'Manicura Gel', price: 35.00, category: 'Manicura Gel', image: 'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?w=400&q=80', description: 'Esmaltado en gel duradero' },
      { name: 'Uñas Acrílicas', price: 55.00, category: 'Uñas Acrílicas', image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&q=80', description: 'Diseño personalizado' },
      { name: 'Nail Art 3D', price: 45.00, category: 'Nail Art 3D', image: 'https://images.unsplash.com/photo-1632345031435-8727f6897d53?w=400&q=80', description: 'Decoración 3D exclusiva' },
    ],
  },

  estilosmirka: {
    id: 'estilosmirka',
    name: 'Estilos Mirka',
    category: 'Moda',
    heroImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&q=80',
    heroAlt: 'Boutique de ropa premium con estilo sofisticado',
    theme: {
      primary: '#6B1A2C',
      onPrimary: '#ffffff',
      primaryContainer: '#3d0d18',
      secondary: '#c8a4ae',
      secondaryContainer: '#f5e8eb',
      background: '#fdf6f7',
      surface: '#ffffff',
      surfaceContainer: '#f5e8eb',
      surfaceContainerLow: '#fdf6f7',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#ead4d9',
      onBackground: '#1a0a0d',
      onSurface: '#1a0a0d',
      onSurfaceVariant: '#6b3a42',
      outlineVariant: '#e0c4ca',
      fontHeadline: "'Playfair Display', serif",
      fontBody: "'Montserrat', sans-serif",
      fontLabel: "'Montserrat', sans-serif",
    },
    categories: [
      { name: 'Vestidos', icon: 'styler', href: 'vestidos' },
      { name: 'Blusas', icon: 'checkroom', href: 'blusas' },
      { name: 'Pantalones', icon: 'accessibility_new', href: 'pantalones' },
      { name: 'Accesorios', icon: 'diamond', href: 'accesorios' },
    ],
    demoProducts: [
      { name: 'Vestido Floral', price: 89.00, category: 'Vestidos', image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&q=80', description: 'Vestido largo con estampado floral' },
      { name: 'Blusa Seda', price: 65.00, category: 'Blusas', image: 'https://images.unsplash.com/photo-1554568218-0f1715e72254?w=400&q=80', description: 'Blusa de seda natural' },
      { name: 'Pantalón Palazzo', price: 75.00, category: 'Pantalones', image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&q=80', description: 'Pantalón ancho de tiro alto' },
    ],
    zona: 'Miraflores',
    direccion: 'Av. Larco 345, Miraflores, Lima',
    horario: 'Lunes a Sábado: 10:00 AM – 08:00 PM',
    rating: 4.8,
  },

  mirkavisual: {
    id: 'mirkavisual',
    name: 'Estilos Mirka (Banner Gráfico)',
    category: 'Moda',
    heroImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1600&q=80',
    heroAlt: 'Boutique con portada visual limpia sin textos encima',
    theme: {
      primary: '#6B1A2C',
      onPrimary: '#ffffff',
      primaryContainer: '#3d0d18',
      secondary: '#c8a4ae',
      secondaryContainer: '#f5e8eb',
      background: '#fdf6f7',
      surface: '#ffffff',
      surfaceContainer: '#f5e8eb',
      surfaceContainerLow: '#fdf6f7',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#ead4d9',
      onBackground: '#1a0a0d',
      onSurface: '#1a0a0d',
      onSurfaceVariant: '#6b3a42',
      outlineVariant: '#e0c4ca',
      fontHeadline: "'Playfair Display', serif",
      fontBody: "'Montserrat', sans-serif",
      fontLabel: "'Montserrat', sans-serif",
    },
    categories: [
      { name: 'Vestidos', icon: 'styler', href: 'vestidos' },
      { name: 'Blusas', icon: 'checkroom', href: 'blusas' },
      { name: 'Pantalones', icon: 'accessibility_new', href: 'pantalones' },
      { name: 'Accesorios', icon: 'diamond', href: 'accesorios' },
    ],
    demoProducts: [
      { name: 'Vestido Floral', price: 89.00, category: 'Vestidos', image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&q=80', description: 'Vestido largo con estampado floral' },
      { name: 'Blusa Seda', price: 65.00, category: 'Blusas', image: 'https://images.unsplash.com/photo-1554568218-0f1715e72254?w=400&q=80', description: 'Blusa de seda natural' },
      { name: 'Pantalón Palazzo', price: 75.00, category: 'Pantalones', image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&q=80', description: 'Pantalón ancho de tiro alto' },
    ],
    zona: 'Miraflores',
    direccion: 'Av. Larco 345, Miraflores, Lima',
    horario: 'Lunes a Sábado: 10:00 AM – 08:00 PM',
    rating: 4.8,
  },

  atelier: {
    id: 'atelier',
    name: 'Atelier Moda',
    category: 'Moda',
    heroImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1600&q=85',
    heroAlt: 'Estudio de moda y boutique contemporánea',
    theme: {
      primary: '#18181b',
      onPrimary: '#ffffff',
      primaryContainer: '#f4f4f5',
      secondary: '#71717a',
      secondaryContainer: '#f4f4f5',
      background: '#fafafa',
      surface: '#ffffff',
      surfaceContainer: '#f4f4f5',
      surfaceContainerLow: '#fafafa',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#e4e4e7',
      onBackground: '#09090b',
      onSurface: '#09090b',
      onSurfaceVariant: '#52525b',
      outlineVariant: '#e4e4e7',
      fontHeadline: "'Outfit', sans-serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontLabel: "'Plus Jakarta Sans', sans-serif",
    },
    categories: [
      { name: 'Vestidos', icon: 'styler', href: 'vestidos' },
      { name: 'Tops & Blusas', icon: 'checkroom', href: 'tops' },
      { name: 'Pantalones & Jeans', icon: 'accessibility_new', href: 'pantalones' },
      { name: 'Conjuntos', icon: 'apparel', href: 'conjuntos' },
    ],
    demoProducts: [
      {
        name: 'Conjunto Guinda Elegance',
        price: 60.00,
        category: 'Conjuntos',
        image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80',
        description: 'Conjunto de dos piezas en tela acanalada premium con caída suave.',
        presentaciones: [
          { label: 'S', price: 60.00 },
          { label: 'M', price: 60.00 },
          { label: 'L', price: 60.00 },
        ],
      },
      {
        name: 'Enterizo Lila Casual',
        price: 60.00,
        category: 'Conjuntos',
        image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&q=80',
        description: 'Enterizo corto de pana suave con tirantes ajustables y bolsillos frontales.',
        presentaciones: [
          { label: 'S', price: 60.00 },
          { label: 'M', price: 60.00 },
        ],
      },
      {
        name: 'Pantalón Palazo Tiro Alto',
        price: 55.00,
        category: 'Pantalones & Jeans',
        image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80',
        description: 'Pantalón ancho en lino suave con lazo en cintura para un look estilizado.',
        presentaciones: [
          { label: 'S', price: 55.00 },
          { label: 'M', price: 55.00 },
          { label: 'L', price: 55.00 },
        ],
      },
      {
        name: 'Vestido Satinado Night Out',
        price: 75.00,
        category: 'Vestidos',
        image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80',
        description: 'Vestido de tirantes en satén brillante, ideal para ocasiones especiales y salidas nocturnas.',
        presentaciones: [
          { label: 'XS', price: 75.00 },
          { label: 'S', price: 75.00 },
          { label: 'M', price: 75.00 },
        ],
      },
    ],
    zona: 'San Isidro',
    direccion: 'Av. Conquistadores 450, Lima',
    horario: 'Lunes a Domingo: 10:00 AM – 09:00 PM',
    rating: 4.9,
    whatsapp: '51987654321',
  },

  lookbook: {
    id: 'lookbook',
    name: 'Lookbook Moda (Banner Gráfico)',
    category: 'Moda',
    heroImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1600&q=85',
    heroAlt: 'Portada gráfica de campaña de moda',
    theme: {
      primary: '#18181b',
      onPrimary: '#ffffff',
      primaryContainer: '#f4f4f5',
      secondary: '#71717a',
      secondaryContainer: '#f4f4f5',
      background: '#ffffff',
      surface: '#ffffff',
      surfaceContainer: '#f4f4f5',
      surfaceContainerLow: '#fafafa',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#e4e4e7',
      onBackground: '#18181b',
      onSurface: '#18181b',
      onSurfaceVariant: '#52525b',
      outlineVariant: '#e4e4e7',
      fontHeadline: "'Outfit', sans-serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontLabel: "'Plus Jakarta Sans', sans-serif",
    },
    categories: [
      { name: 'Vestidos', icon: 'styler', href: 'vestidos' },
      { name: 'Tops & Blusas', icon: 'checkroom', href: 'tops' },
      { name: 'Pantalones & Jeans', icon: 'accessibility_new', href: 'pantalones' },
      { name: 'Conjuntos', icon: 'apparel', href: 'conjuntos' },
    ],
    demoProducts: [
      {
        name: 'Conjunto Guinda Elegance',
        price: 60.00,
        category: 'Conjuntos',
        image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80',
        description: 'Conjunto de dos piezas en tela acanalada premium con caída suave.',
        presentaciones: [
          { label: 'S', price: 60.00 },
          { label: 'M', price: 60.00 },
          { label: 'L', price: 60.00 },
        ],
      },
      {
        name: 'Enterizo Lila Casual',
        price: 60.00,
        category: 'Conjuntos',
        image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&q=80',
        description: 'Enterizo corto de pana suave con tirantes ajustables y bolsillos frontales.',
        presentaciones: [
          { label: 'S', price: 60.00 },
          { label: 'M', price: 60.00 },
        ],
      },
      {
        name: 'Pantalón Palazo Tiro Alto',
        price: 55.00,
        category: 'Pantalones & Jeans',
        image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80',
        description: 'Pantalón ancho en lino suave con lazo en cintura para un look estilizado.',
        presentaciones: [
          { label: 'S', price: 55.00 },
          { label: 'M', price: 55.00 },
          { label: 'L', price: 55.00 },
        ],
      },
      {
        name: 'Vestido Satinado Night Out',
        price: 75.00,
        category: 'Vestidos',
        image: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&q=80',
        description: 'Vestido de tirantes en satén brillante, ideal para ocasiones especiales y salidas nocturnas.',
        presentaciones: [
          { label: 'XS', price: 75.00 },
          { label: 'S', price: 75.00 },
          { label: 'M', price: 75.00 },
        ],
      },
    ],
    zona: 'Miraflores',
    direccion: 'Calle Esperanza 280, Lima',
    horario: 'Lunes a Domingo: 10:00 AM – 09:00 PM',
    rating: 4.9,
    whatsapp: '51987654321',
  },

  discoteca: {
    id: 'discoteca',
    name: 'Discoteca & Club Nocturno (Neon Lounge)',
    category: 'Nocturno',
    heroImage: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=1600&q=85',
    heroAlt: 'Luces láser y fiesta en discoteca club nocturno',
    theme: {
      primary: '#a855f7',
      onPrimary: '#ffffff',
      primaryContainer: '#06b6d4',
      secondary: '#ec4899',
      secondaryContainer: '#1e1b4b',
      background: '#09090b',
      surface: '#0f172a',
      surfaceContainer: '#18181b',
      surfaceContainerLow: '#09090b',
      surfaceContainerLowest: '#030712',
      surfaceContainerHigh: '#27272a',
      onBackground: '#f8fafc',
      onSurface: '#f8fafc',
      onSurfaceVariant: '#94a3b8',
      outlineVariant: '#27272a',
      fontHeadline: "'Outfit', sans-serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontLabel: "'Outfit', sans-serif",
    },
    categories: [
      { name: 'Combos & Botellas', icon: 'liquor', href: 'botellas' },
      { name: 'Boxes VIP', icon: 'stars', href: 'boxes' },
      { name: 'Tragos & Cócteles', icon: 'local_bar', href: 'cocteles' },
      { name: 'Cervezas Heladas', icon: 'sports_bar', href: 'cervezas' },
      { name: 'Entradas & Pases', icon: 'confirmation_number', href: 'entradas' },
      { name: 'Piques & Snacks', icon: 'lunch_dining', href: 'piques' },
    ],
    demoProducts: [
      {
        name: 'Combo Johnnie Walker Black Label',
        price: 220.00,
        category: 'botellas',
        image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=800&q=80',
        description: 'Botella Johnnie Walker Black Label 750ml + 4 Red Bull + hielo ilimitado + vaso highball.',
        presentaciones: [
          { label: 'Botella Sola', price: 180.00 },
          { label: 'Combo + 4 Red Bull', price: 220.00 },
          { label: 'Combo Gold + 6 Red Bull', price: 260.00 },
        ],
      },
      {
        name: 'Box VIP Ultra Lounge (10 Personas)',
        price: 850.00,
        category: 'boxes',
        image: 'https://images.unsplash.com/photo-1578474846511-04ba529f0b88?w=800&q=80',
        description: 'Mesa y sillón lounge exclusivo, 10 pulseras VIP sin cola, 2 botellas de whisky o vodka y atención de mozo dedicada.',
        presentaciones: [
          { label: 'Box Silver (1 Botella)', price: 550.00 },
          { label: 'Box Gold (2 Botellas)', price: 850.00 },
          { label: 'Box Platinum All-Inclusive', price: 1200.00 },
        ],
      },
      {
        name: 'Combo Vodka Absolut Blue + Néctar',
        price: 170.00,
        category: 'botellas',
        image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&q=80',
        description: 'Vodka Absolut 750ml + 2 jarras de néctar de naranja/arándano + hielera acrílica con luz LED.',
        presentaciones: [
          { label: 'Botella Sola', price: 135.00 },
          { label: 'Combo con Jugo', price: 170.00 },
          { label: 'Combo con 4 Red Bull', price: 205.00 },
        ],
      },
      {
        name: 'Gin Tonic Beefeater Pink Neon',
        price: 32.00,
        category: 'cocteles',
        image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
        description: 'Copa balón con Gin Beefeater Pink, tónica premium Britvic, fresas maceradas y ramita de menta fresca.',
        presentaciones: [
          { label: 'Copa Balón Simple', price: 32.00 },
          { label: 'Doble Shot Gin', price: 42.00 },
          { label: 'Jarra para 4 Personas', price: 110.00 },
        ],
      },
      {
        name: 'Balde Corona Extra (6 Unidades Heladas)',
        price: 65.00,
        category: 'cervezas',
        image: 'https://images.unsplash.com/photo-1608270192770-5b51b72e5fc4?w=800&q=80',
        description: 'Balde metálico con hielo frappé, 6 cervezas Corona 330ml heladas y gajos de limón.',
        presentaciones: [
          { label: 'Balde 6 Unid.', price: 65.00 },
          { label: 'Balde 10 Unid.', price: 100.00 },
        ],
      },
      {
        name: 'Entrada VIP Fast Pass + Cover',
        price: 40.00,
        category: 'entradas',
        image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80',
        description: 'Ingreso directo sin colas toda la noche + 1 trago de cortesía en la barra VIP del segundo nivel.',
        presentaciones: [
          { label: 'General con Trago', price: 25.00 },
          { label: 'VIP Fast Pass', price: 40.00 },
          { label: 'Golden All Night Pass', price: 60.00 },
        ],
      },
      {
        name: 'Tequeños Rellenos con Queso & Guacamole',
        price: 28.00,
        category: 'piques',
        image: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=800&q=80',
        description: '12 tequeños crocantes rellenos de abundante queso andino fundido, acompañados de crema de guacamole.',
      },
    ],
    zona: 'Zona Rosa / Malecón',
    direccion: 'Av. Las Palmas 540',
    horario: 'Jueves a Sábado: 09:00 PM – 05:00 AM',
    rating: 4.9,
    whatsapp: '51987654321',
  },

  cartelera: {
    id: 'cartelera',
    name: 'Cartelera & Club de Eventos (Fechas & Entradas)',
    category: 'Nocturno',
    heroImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1600&q=85',
    heroAlt: 'Concierto y cartelera de eventos en club nocturno',
    theme: {
      primary: '#8b5cf6',
      onPrimary: '#ffffff',
      primaryContainer: '#06b6d4',
      secondary: '#ec4899',
      secondaryContainer: '#1e1b4b',
      background: '#07070a',
      surface: '#0f0f18',
      surfaceContainer: '#141420',
      surfaceContainerLow: '#09090f',
      surfaceContainerLowest: '#030305',
      surfaceContainerHigh: '#20202e',
      onBackground: '#f8fafc',
      onSurface: '#f8fafc',
      onSurfaceVariant: '#94a3b8',
      outlineVariant: '#27272a',
      fontHeadline: "'Outfit', sans-serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontLabel: "'Outfit', sans-serif",
    },
    categories: [
      { name: 'Próximos Eventos', icon: 'event', href: 'eventos' },
      { name: 'Combos & Botellas', icon: 'liquor', href: 'botellas' },
      { name: 'Boxes VIP', icon: 'stars', href: 'boxes' },
      { name: 'Tragos & Cócteles', icon: 'local_bar', href: 'cocteles' },
      { name: 'Cervezas', icon: 'sports_bar', href: 'cervezas' },
    ],
    demoProducts: [
      {
        name: 'Combo Johnnie Walker Gold Label',
        price: 320.00,
        category: 'botellas',
        image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=800&q=80',
        description: 'Botella Gold Label Reserve 750ml + 6 Red Bull Tropical + hielera LED.',
        presentaciones: [
          { label: 'Botella Sola', price: 270.00 },
          { label: 'Combo + 4 Red Bull', price: 320.00 },
          { label: 'Combo + 6 Red Bull', price: 350.00 },
        ],
      },
      {
        name: 'Box VIP Ultra Stage (12 Personas)',
        price: 950.00,
        category: 'boxes',
        image: 'https://images.unsplash.com/photo-1578474846511-04ba529f0b88?w=800&q=80',
        description: 'Mesa y sillón lounge exclusivo al lado del escenario, 12 pulseras VIP sin cola, 2 botellas de whisky o vodka y atención de mozo dedicada.',
        presentaciones: [
          { label: 'Box Silver (1 Botella)', price: 600.00 },
          { label: 'Box Gold (2 Botellas)', price: 950.00 },
          { label: 'Box All-Inclusive (3 Botellas)', price: 1350.00 },
        ],
      },
      {
        name: 'Chilcano Macerado de Hierbaluisa',
        price: 28.00,
        category: 'cocteles',
        image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80',
        description: 'Pisco macerado en casa con hierbaluisa fresca, ginger ale premium y gotas de amargo de angostura.',
        presentaciones: [
          { label: 'Vaso 16 oz', price: 28.00 },
          { label: 'Doble Golpe', price: 38.00 },
          { label: 'Jarra de 1.5 Litros', price: 95.00 },
        ],
      },
      {
        name: 'Balde Heineken Heladas (6 Botellas)',
        price: 70.00,
        category: 'cervezas',
        image: 'https://images.unsplash.com/photo-1608270192770-5b51b72e5fc4?w=800&q=80',
        description: 'Balde metálico con hielo frappé, 6 cervezas Heineken 330ml heladas.',
        presentaciones: [
          { label: 'Balde 6 Unid.', price: 70.00 },
          { label: 'Balde 10 Unid.', price: 110.00 },
        ],
      },
    ],
    zona: 'Zona Rosa / Malecón',
    direccion: 'Av. Las Palmas 540',
    horario: 'Jueves a Sábado: 09:00 PM – 05:00 AM',
    rating: 4.9,
    whatsapp: '51987654321',
  },

  mercado: {
    id: 'mercado',
    name: 'Mercado BogaHub',
    category: 'Mercado',
    heroImage: 'https://images.unsplash.com/photo-1580913428735-bd3c269d6a82?w=1200&q=80',
    heroAlt: 'Pasillo de minimarket surtido con productos de abarrotes',
    theme: {
      primary: '#b8130e',
      onPrimary: '#ffffff',
      primaryContainer: '#dc3225',
      secondary: '#5f5e5e',
      secondaryContainer: '#e2dfde',
      background: '#f8f9fa',
      surface: '#ffffff',
      surfaceContainer: '#edeeef',
      surfaceContainerLow: '#f3f4f5',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#e7e8e9',
      onBackground: '#191c1d',
      onSurface: '#191c1d',
      onSurfaceVariant: '#5c403c',
      outlineVariant: '#e1e3e4',
      fontHeadline: "'Outfit', sans-serif",
      fontBody: "'Outfit', sans-serif",
      fontLabel: "'Outfit', sans-serif",
    },
    // Pensadas para una bodega o comercial de barrio (no un supermercado): son los cuatro rubros de siempre.
    categories: [
      { name: 'Abarrotes y despensa', icon: 'shopping_basket', href: 'abarrotes' },
      { name: 'Limpieza del hogar', icon: 'cleaning_services', href: 'limpieza' },
      { name: 'Higiene personal', icon: 'face_6', href: 'higiene' },
      { name: 'Productos para el hogar', icon: 'home', href: 'hogar' },
    ],
    demoProducts: [
      { name: 'Arroz Extra 5kg', price: 24.90, category: 'Abarrotes y despensa', image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80', description: 'Arroz de grano extra largo' },
      { name: 'Aceite Vegetal 1L', price: 9.50, category: 'Abarrotes y despensa', image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&q=80', description: 'Aceite vegetal puro' },
      { name: 'Leche Entera 1L', price: 4.80, category: 'Abarrotes y despensa', image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&q=80', description: 'Leche entera pasteurizada' },
      { name: 'Galletas Pack x6', price: 6.50, category: 'Abarrotes y despensa', image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&q=80', description: 'Surtido de galletas' },
      { name: 'Detergente 2kg', price: 18.00, category: 'Limpieza del hogar', image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?w=400&q=80', description: 'Detergente en polvo multiusos' },
      { name: 'Lejía 1/4 de litro', price: 6.00, category: 'Limpieza del hogar', image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&q=80', description: 'Desinfectante para pisos y baños' },
      { name: 'Limpiador cremoso', price: 7.50, category: 'Higiene personal', image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&q=80', description: 'Limpiador facial suave de uso diario' },
    ],
  },

  // Catálogo por peso (especias, condimentos, granos, frutos secos): cada producto se pide en 100 g / 250 g / 1 kg.
  // Reusa la pantalla de "mercado" (templates/mercado), que es la que sabe elegir la medida.
  condimentos: {
    id: 'condimentos',
    name: 'Condimentos y Especias',
    category: 'Mercado',
    heroImage: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=1200&q=80',
    heroAlt: 'Especias y hierbas variadas sobre una mesa',
    theme: {
      primary: '#b45309',
      onPrimary: '#ffffff',
      primaryContainer: '#d97706',
      secondary: '#5f5e5e',
      secondaryContainer: '#e2dfde',
      background: '#fbf7f0',
      surface: '#ffffff',
      surfaceContainer: '#f3ece1',
      surfaceContainerLow: '#f8f2e8',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#ebe2d3',
      onBackground: '#2b1d0e',
      onSurface: '#2b1d0e',
      onSurfaceVariant: '#6b4a2b',
      outlineVariant: '#e6dccb',
      fontHeadline: "'Outfit', sans-serif",
      fontBody: "'Outfit', sans-serif",
      fontLabel: "'Outfit', sans-serif",
    },
    categories: [
      { name: 'Molidos', icon: 'grain', href: 'molidos' },
      { name: 'Ajíes', icon: 'local_fire_department', href: 'ajies' },
      { name: 'Hierbas', icon: 'grass', href: 'hierbas' },
      { name: 'Especias enteras', icon: 'spa', href: 'especias-enteras' },
    ],
    demoProducts: [
      { name: 'Comino molido', price: 3.5, category: 'Molidos', image: 'https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=400&q=80', description: 'Comino molido fino, aroma intenso. Ideal para carnes, guisos y menestras.', presentaciones: [{ label: '100 g', price: 3.5 }, { label: '250 g', price: 8 }, { label: '1 kg', price: 28 }] },
      { name: 'Pimienta negra molida', price: 5, category: 'Molidos', image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80', description: 'Pimienta negra recién molida. Para todo tipo de sazón.', presentaciones: [{ label: '100 g', price: 5 }, { label: '250 g', price: 11.5 }, { label: '1 kg', price: 40 }] },
      { name: 'Palillo molido', price: 3, category: 'Molidos', image: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&q=80', description: 'Palillo (cúrcuma) molido: color y sabor para arroces y guisos.', presentaciones: [{ label: '100 g', price: 3 }, { label: '250 g', price: 7 }, { label: '1 kg', price: 24 }] },
      { name: 'Ajo molido', price: 4, category: 'Molidos', image: 'https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=400&q=80', description: 'Ajo deshidratado y molido, práctico para toda la cocina.', presentaciones: [{ label: '100 g', price: 4 }, { label: '250 g', price: 9 }, { label: '1 kg', price: 30 }] },
      { name: 'Ají panca molido', price: 3, category: 'Ajíes', image: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&q=80', description: 'Ají panca molido, base de adobos y guisos criollos.', presentaciones: [{ label: '100 g', price: 3 }, { label: '250 g', price: 7 }, { label: '1 kg', price: 22 }] },
      { name: 'Ají amarillo molido', price: 3.5, category: 'Ajíes', image: 'https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=400&q=80', description: 'Ají amarillo molido, el sabor de la cocina peruana.', presentaciones: [{ label: '100 g', price: 3.5 }, { label: '250 g', price: 8 }, { label: '1 kg', price: 26 }] },
      { name: 'Orégano seco', price: 4, category: 'Hierbas', image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80', description: 'Orégano seco, aromático. Para pizzas, adobos y aderezos.', presentaciones: [{ label: '100 g', price: 4 }, { label: '250 g', price: 9 }, { label: '1 kg', price: 30 }] },
      { name: 'Canela en rama', price: 6, category: 'Especias enteras', image: 'https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=400&q=80', description: 'Canela en rama seleccionada, para mazamorras, chicha y postres.', presentaciones: [{ label: '100 g', price: 6 }, { label: '250 g', price: 14 }, { label: '1 kg', price: 48 }] },
    ],
    zona: 'Pucallpa',
    direccion: 'Mercado Modelo, Pucallpa',
    horario: 'Lunes a Sábado: 7:00 AM – 6:00 PM',
    rating: 4.8,
  },

  polleria: {
    id: 'polleria',
    name: 'Pollería Bravoz',
    category: 'Restaurantes',
    heroImage: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=1200&q=80',
    heroAlt: 'Pollo a la brasa dorado crujiente con papas fritas',
    iconImage: '/icons/polleria.svg',
    theme: {
      primary: '#a43800',
      onPrimary: '#ffffff',
      primaryContainer: '#ffdbce',
      secondary: '#7a574d',
      secondaryContainer: '#f8ded7',
      background: '#fdf8f6',
      surface: '#ffffff',
      surfaceContainer: '#fceee9',
      surfaceContainerLow: '#fdf8f6',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#f3e0d8',
      onBackground: '#231a17',
      onSurface: '#231a17',
      onSurfaceVariant: '#53433e',
      outlineVariant: '#e8d0ca',
      fontHeadline: "'Plus Jakarta Sans', sans-serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontLabel: "'Plus Jakarta Sans', sans-serif",
    },
    categories: [
      { name: 'Pollos a la Brasa', icon: 'local_fire_department', href: 'brasa' },
      { name: 'Combos', icon: 'takeout_dining', href: 'combos' },
      { name: 'Parrillas', icon: 'outdoor_grill', href: 'parrillas' },
      { name: 'Bebidas', icon: 'local_bar', href: 'bebidas' },
    ],
    demoProducts: [
      { name: '1/4 Pollo a la Brasa', price: 22.90, category: 'Pollos a la Brasa', image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=400&q=80', description: 'Con papas y ensalada fresca' },
      { name: 'Combo 6 Alitas', price: 18.00, category: 'Combos', image: 'https://images.unsplash.com/photo-1610614819513-58e34989848b?w=400&q=80', description: 'Bañadas en salsa BBQ o Spicy' },
      { name: 'Parrilla Mixta', price: 54.00, category: 'Parrillas', image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80', description: 'Pollo, res y embutidos' },
      { name: 'Inca Kola 1L', price: 7.00, category: 'Bebidas', image: 'https://images.unsplash.com/photo-1625943553852-781c6dd46faa?w=400&q=80', description: 'Gaseosa peruana bien helada' },
    ],
    zona: 'Miraflores',
    direccion: 'Av. Fuego y Brasa 1995, Miraflores, Lima',
    horario: 'Lunes a Domingo: 12:00 PM – 11:00 PM',
    rating: 4.8,
  },

  // Comparte motor con "polleria" (templates/shared): cambia como se arma la
  // pantalla, no la logica de catalogo, carrito ni pedidos.
  menudirecto: {
    id: 'menudirecto',
    name: 'Menú Directo',
    category: 'Restaurantes',
    heroImage: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1200&q=80',
    heroAlt: 'Hamburguesa artesanal con papas sobre tabla de madera',
    theme: {
      primary: '#b3261e',
      onPrimary: '#ffffff',
      primaryContainer: '#ffdad6',
      secondary: '#775652',
      secondaryContainer: '#ffdad6',
      background: '#fffbff',
      surface: '#ffffff',
      surfaceContainer: '#fceae7',
      surfaceContainerLow: '#fff8f7',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#f6e4e1',
      onBackground: '#201a19',
      onSurface: '#201a19',
      onSurfaceVariant: '#534341',
      outlineVariant: '#e9d6d3',
      fontHeadline: "'Plus Jakarta Sans', sans-serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontLabel: "'Plus Jakarta Sans', sans-serif",
    },
    categories: [
      { name: 'Hamburguesas', icon: 'lunch_dining', href: 'hamburguesas' },
      { name: 'Al Plato', icon: 'restaurant', href: 'alplato' },
      { name: 'Para Compartir', icon: 'takeout_dining', href: 'compartir' },
      { name: 'Bebidas', icon: 'local_bar', href: 'bebidas' },
    ],
    demoProducts: [
      { name: 'Hamburguesa Clásica', price: 19.90, category: 'Hamburguesas', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80', description: 'Carne, queso cheddar y salsa de la casa' },
      { name: 'Lomo Saltado', price: 32.00, category: 'Al Plato', image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&q=80', description: 'Con papas fritas y arroz graneado' },
      { name: 'Piqueo para 2', price: 45.00, category: 'Para Compartir', image: 'https://images.unsplash.com/photo-1610614819513-58e34989848b?w=400&q=80', description: 'Alitas, tequeños y papas rústicas' },
      { name: 'Limonada Frozen', price: 9.50, category: 'Bebidas', image: 'https://images.unsplash.com/photo-1625943553852-781c6dd46faa?w=400&q=80', description: 'Jarra de medio litro bien helada' },
      { name: 'Combo Burger + Papas + Gaseosa', price: 24.90, category: 'Hamburguesas', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80', description: 'Hamburguesa clásica, papas fritas y gaseosa personal', esCombo: true },
      { name: 'Piqueo para 2 + Jarra', price: 49.00, category: 'Para Compartir', image: 'https://images.unsplash.com/photo-1610614819513-58e34989848b?w=400&q=80', description: 'Alitas, tequeños, papas rústicas y una jarra de limonada', esCombo: true, priceAnterior: 58.00 },
    ],
    zona: 'Miraflores',
    direccion: 'Av. Fuego y Brasa 1995, Miraflores, Lima',
    horario: '12–11PM',
  },

  iniciocatalogo: {
    id: 'iniciocatalogo',
    name: 'Inicio con Catálogo',
    category: 'Restaurantes',
    heroImage: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1200&q=80',
    heroAlt: 'Parrilla con carnes y verduras a la brasa',
    theme: {
      primary: '#8f4c00',
      onPrimary: '#ffffff',
      primaryContainer: '#ffdcc2',
      secondary: '#755846',
      secondaryContainer: '#ffdcc2',
      background: '#fffbff',
      surface: '#ffffff',
      surfaceContainer: '#f9ece4',
      surfaceContainerLow: '#fff8f4',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#f2e5dd',
      onBackground: '#211a15',
      onSurface: '#211a15',
      onSurfaceVariant: '#52443b',
      outlineVariant: '#e5d3c7',
      fontHeadline: "'Plus Jakarta Sans', sans-serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontLabel: "'Plus Jakarta Sans', sans-serif",
    },
    categories: [
      { name: 'Parrillas', icon: 'outdoor_grill', href: 'parrillas' },
      { name: 'Entradas', icon: 'ramen_dining', href: 'entradas' },
      { name: 'Guarniciones', icon: 'rice_bowl', href: 'guarniciones' },
      { name: 'Postres', icon: 'icecream', href: 'postres' },
      { name: 'Bebidas', icon: 'local_bar', href: 'bebidas' },
    ],
    demoProducts: [
      { name: 'Parrilla Familiar', price: 89.00, category: 'Parrillas', image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80', description: 'Res, pollo, chorizo y anticuchos' },
      { name: 'Anticuchos (4u)', price: 24.00, category: 'Entradas', image: 'https://images.unsplash.com/photo-1610614819513-58e34989848b?w=400&q=80', description: 'Con papa dorada y choclo' },
      { name: 'Ensalada Criolla', price: 12.00, category: 'Guarniciones', image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&q=80', description: 'Cebolla, tomate y limón' },
      { name: 'Suspiro Limeño', price: 14.00, category: 'Postres', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&q=80', description: 'Manjar blanco y merengue al oporto' },
      { name: 'Chicha Morada 1L', price: 10.00, category: 'Bebidas', image: 'https://images.unsplash.com/photo-1625943553852-781c6dd46faa?w=400&q=80', description: 'Preparada en casa, sin polvos' },
    ],
    zona: 'Miraflores',
    direccion: 'Av. Fuego y Brasa 1995, Miraflores, Lima',
    horario: '12–11PM',
  },
  flores: {
    id: 'flores',
    name: 'Florería',
    category: 'Comercio',
    heroImage: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=1200&q=80',
    heroAlt: 'Ramos y arreglos de flores frescas',
    theme: {
      primary: '#2f6b4f',
      onPrimary: '#ffffff',
      primaryContainer: '#dcefe3',
      secondary: '#c2185b',
      secondaryContainer: '#fde3ec',
      background: '#f8fbf8',
      surface: '#ffffff',
      surfaceContainer: '#eaf3ec',
      surfaceContainerLow: '#f8fbf8',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#dfeae2',
      onBackground: '#1d2a22',
      onSurface: '#1d2a22',
      onSurfaceVariant: '#506358',
      outlineVariant: '#d3e2d8',
      fontHeadline: "'Playfair Display', serif",
      fontBody: "'Outfit', sans-serif",
      fontLabel: "'Outfit', sans-serif",
    },
    categories: [
      { name: 'San Valentín', icon: 'favorite', href: 'san-valentin' },
      { name: 'Ramos', icon: 'local_florist', href: 'ramos' },
      { name: 'Arreglos', icon: 'yard', href: 'arreglos' },
      { name: 'Plantas', icon: 'potted_plant', href: 'plantas' },
      { name: 'Detalles', icon: 'redeem', href: 'detalles' },
    ],
    demoProducts: [
      { name: 'Ramo San Valentín 24 Rosas', price: 120.00, category: 'San Valentín', image: 'https://images.unsplash.com/photo-1455659817273-f96807779a8a?w=600&q=80', description: 'Rosas rojas con follaje y lazo. Solo para San Valentín.' },
      { name: 'Ramo de Rosas Rojas', price: 65.00, category: 'Ramos', image: 'https://images.unsplash.com/photo-1455659817273-f96807779a8a?w=600&q=80', description: '12 rosas rojas frescas con follaje' },
      { name: 'Caja de Girasoles', price: 70.00, category: 'Ramos', image: 'https://images.unsplash.com/photo-1563241527-3004b7be0ffd?w=600&q=80', description: 'Girasoles frescos en caja sorpresa' },
      { name: 'Arreglo Primaveral', price: 85.00, category: 'Arreglos', image: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=600&q=80', description: 'Mix de flores de temporada en base de cerámica' },
      { name: 'Orquídea en Maceta', price: 55.00, category: 'Plantas', image: 'https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=600&q=80', description: 'Orquídea Phalaenopsis lista para regalar' },
      { name: 'Peluche + Flores', price: 95.00, category: 'Detalles', image: 'https://images.unsplash.com/photo-1462530260150-162092dbf011?w=600&q=80', description: 'Ramo pequeño con peluche y chocolates' },
    ],
    zona: 'Pucallpa',
    horario: 'Lunes a Domingo: 8:00 AM – 8:00 PM',
    rating: 4.9,
  },
  detalles: {
    id: 'detalles',
    name: 'Detalles Hechos a Mano',
    category: 'Comercio',
    heroImage: 'https://images.unsplash.com/photo-1546552768-9e3a94b38a59?w=1200&q=80',
    heroAlt: 'Jabones artesanales y velas hechos a mano',
    theme: {
      primary: '#b4536a',
      onPrimary: '#ffffff',
      primaryContainer: '#f7dde3',
      secondary: '#7a8f6b',
      secondaryContainer: '#e4ebdc',
      background: '#fbf6f1',
      surface: '#ffffff',
      surfaceContainer: '#f4ebe3',
      surfaceContainerLow: '#fbf6f1',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#eddfd3',
      onBackground: '#2e2224',
      onSurface: '#2e2224',
      onSurfaceVariant: '#6e5a5d',
      outlineVariant: '#e6d6ca',
      fontHeadline: "'Playfair Display', serif",
      fontBody: "'Outfit', sans-serif",
      fontLabel: "'Outfit', sans-serif",
    },
    categories: [
      { name: 'San Valentín', icon: 'favorite', href: 'san-valentin' },
      { name: 'Jabones', icon: 'soap', href: 'jabones' },
      { name: 'Velas', icon: 'local_fire_department', href: 'velas' },
      { name: 'Adornos en MDF', icon: 'carpenter', href: 'mdf' },
      { name: 'Cerámica al frío', icon: 'palette', href: 'ceramica' },
    ],
    demoProducts: [
      { name: 'Pack Día de los Enamorados', price: 45.00, category: 'San Valentín', image: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?w=600&q=80', description: 'Jabón en forma de corazón + vela aromática. Diseño solo de esta temporada.' },
      { name: 'Jabón Corazón de Rosas', price: 12.00, category: 'San Valentín', image: 'https://images.unsplash.com/photo-1546552768-9e3a94b38a59?w=600&q=80', description: 'Edición limitada, hecho a mano con pétalos de rosa.' },
      { name: 'Jabón de Lavanda', price: 8.00, category: 'Jabones', image: 'https://images.unsplash.com/photo-1546552768-9e3a94b38a59?w=600&q=80', description: 'Jabón artesanal de glicerina con aroma a lavanda.' },
      { name: 'Jabón Temático de Animalitos', price: 10.00, category: 'Jabones', image: 'https://images.unsplash.com/photo-1546552768-9e3a94b38a59?w=600&q=80', description: 'Ideal para souvenirs y cumpleaños. Se hace por pedido.' },
      { name: 'Vela Aromática de Soya', price: 18.00, category: 'Velas', image: 'https://images.unsplash.com/photo-1613068431228-8cb6a1e92573?w=600&q=80', description: 'Vela temática en frasco, aroma vainilla.' },
      { name: 'Adorno en MDF Personalizado', price: 15.00, category: 'Adornos en MDF', image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&q=80', description: 'Pintado a mano, con el nombre que tú quieras.' },
      { name: 'Figura de Cerámica al Frío', price: 22.00, category: 'Cerámica al frío', image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80', description: 'Modelada y pintada a mano, pieza única.' },
    ],
    zona: 'Pucallpa',
    horario: 'Lunes a Sábado: 9:00 AM – 7:00 PM',
    rating: 4.9,
  },
  fichadigital: {
    id: 'fichadigital',
    name: 'Ficha Digital',
    category: 'Restaurantes',
    heroImage: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=1200&q=80',
    heroAlt: 'Ceviche fresco servido con camote y choclo',
    theme: {
      primary: '#00838f',
      onPrimary: '#ffffff',
      primaryContainer: '#004d54',
      secondary: '#37474f',
      secondaryContainer: '#cfe8ea',
      background: '#f4fbfc',
      surface: '#ffffff',
      surfaceContainer: '#e0f2f4',
      surfaceContainerLow: '#f4fbfc',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#d0e9ec',
      onBackground: '#0f2124',
      onSurface: '#0f2124',
      onSurfaceVariant: '#3f5c60',
      outlineVariant: '#c3dde0',
      fontHeadline: "'Plus Jakarta Sans', sans-serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontLabel: "'Plus Jakarta Sans', sans-serif",
    },
    categories: [
      { name: 'Ceviches', icon: 'set_meal', href: 'ceviches' },
      { name: 'Piqueos', icon: 'tapas', href: 'piqueos' },
      { name: 'Arroces', icon: 'rice_bowl', href: 'arroces' },
      { name: 'Bebidas', icon: 'local_bar', href: 'bebidas' },
    ],
    demoProducts: [
      { name: 'Ceviche Clásico', price: 28.00, category: 'Ceviches', image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&q=80', description: 'Pescado fresco, limón, cebolla y camote' },
      { name: 'Tiradito Acevichado', price: 32.00, category: 'Ceviches', image: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=400&q=80', description: 'Finas láminas de pescado en crema de ají' },
      { name: 'Causa de Pulpo', price: 26.00, category: 'Piqueos', image: 'https://images.unsplash.com/photo-1610614819513-58e34989848b?w=400&q=80', description: 'Papa amarilla rellena con pulpo al olivo' },
      { name: 'Arroz con Mariscos', price: 34.00, category: 'Arroces', image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&q=80', description: 'Arroz meloso con mix de mariscos' },
      { name: 'Chicha Morada 1L', price: 10.00, category: 'Bebidas', image: 'https://images.unsplash.com/photo-1625943553852-781c6dd46faa?w=400&q=80', description: 'Preparada en casa, sin polvos' },
    ],
    zona: 'San Juan de Lurigancho - Lima',
    direccion: 'Av. Pampa Chica Mz. O7 Lt. 06, Urb. Casa Blanca',
    horario: '12:00 PM – 11:00 PM',
    rating: 4.7,
    whatsapp: '51987654321',
  },

  fichaplana: {
    id: 'fichaplana',
    name: 'Ficha Plana',
    category: 'Restaurantes',
    heroImage: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=1200&q=80',
    heroAlt: 'Parrilla con carnes a la brasa',
    theme: {
      primary: '#c1440e',
      onPrimary: '#ffffff',
      primaryContainer: '#7a2c09',
      secondary: '#5c4033',
      secondaryContainer: '#f2ddd2',
      background: '#fdf7f4',
      surface: '#ffffff',
      surfaceContainer: '#f7ebe4',
      surfaceContainerLow: '#fdf7f4',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#f0ddd2',
      onBackground: '#241611',
      onSurface: '#241611',
      onSurfaceVariant: '#5c473d',
      outlineVariant: '#e3d0c5',
      fontHeadline: "'Plus Jakarta Sans', sans-serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontLabel: "'Plus Jakarta Sans', sans-serif",
    },
    categories: [
      { name: 'Parrillas', icon: 'outdoor_grill', href: 'parrillas' },
      { name: 'Anticuchos', icon: 'kebab_dining', href: 'anticuchos' },
      { name: 'Guarniciones', icon: 'rice_bowl', href: 'guarniciones' },
      { name: 'Bebidas', icon: 'local_bar', href: 'bebidas' },
    ],
    demoProducts: [
      { name: 'Parrilla Personal', price: 32.00, category: 'Parrillas', image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80', description: 'Res, pollo y chorizo con guarnición' },
      { name: 'Anticuchos (4u)', price: 22.00, category: 'Anticuchos', image: 'https://images.unsplash.com/photo-1610614819513-58e34989848b?w=400&q=80', description: 'Con papa dorada y choclo' },
      { name: 'Papas Rústicas', price: 12.00, category: 'Guarniciones', image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&q=80', description: 'Con salsas de la casa' },
      { name: 'Chicha Morada 1L', price: 10.00, category: 'Bebidas', image: 'https://images.unsplash.com/photo-1625943553852-781c6dd46faa?w=400&q=80', description: 'Preparada en casa, sin polvos' },
    ],
    zona: 'San Juan de Lurigancho - Lima',
    direccion: 'Av. Pampa Chica Mz. O7 Lt. 06, Urb. Casa Blanca',
    horario: '12:00 PM – 11:00 PM',
    rating: 4.6,
    whatsapp: '51987654321',
  },
  veterinaria: {
    id: 'veterinaria',
    name: 'Veterinaria',
    category: 'Salud',
    heroImage: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=1200&q=80',
    heroAlt: 'Perro en la veterinaria',
    theme: {
      primary: '#0f8f7e',
      onPrimary: '#ffffff',
      primaryContainer: '#0a6357',
      secondary: '#4a6360',
      secondaryContainer: '#d5ece8',
      background: '#f4faf9',
      surface: '#ffffff',
      surfaceContainer: '#e8f4f2',
      surfaceContainerLow: '#f4faf9',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#dcedea',
      onBackground: '#10231f',
      onSurface: '#10231f',
      onSurfaceVariant: '#456560',
      outlineVariant: '#c5dcd8',
      fontHeadline: "'Plus Jakarta Sans', sans-serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontLabel: "'Plus Jakarta Sans', sans-serif",
    },
    categories: [
      { name: 'Alimento', icon: 'pet_supplies', href: 'alimento' },
      { name: 'Accesorios', icon: 'pets', href: 'accesorios' },
      { name: 'Higiene', icon: 'bathtub', href: 'higiene' },
      { name: 'Servicios', icon: 'medical_services', href: 'servicios' },
    ],
    demoProducts: [
      { name: 'Alimento para perro adulto 3kg', price: 65.00, category: 'Alimento', image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&q=80', description: 'Croquetas balanceadas' },
      { name: 'Correa y collar', price: 28.00, category: 'Accesorios', image: 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=400&q=80', description: 'Ajustable, varios tamaños' },
      { name: 'Shampoo antipulgas', price: 24.00, category: 'Higiene', image: 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?w=400&q=80', description: 'Uso semanal, pelaje suave' },
      { name: 'Baño y corte', price: 40.00, category: 'Servicios', image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=400&q=80', description: 'Reserva por WhatsApp' },
    ],
    zona: 'Pucallpa - Ucayali',
    direccion: 'Jr. Ucayali 123',
    horario: '9:00 AM – 7:00 PM',
    rating: 4.8,
    whatsapp: '51987654321',
  },
  empresa: {
    id: 'empresa',
    name: 'Empresa de Servicios',
    category: 'Servicios',
    heroImage: '/sel/portada.jpg',
    heroAlt: 'Estructura metálica techada en obra',
    theme: {
      primary: '#2a6496',
      onPrimary: '#ffffff',
      primaryContainer: '#1d4a70',
      secondary: '#1b3b5a',
      secondaryContainer: '#dce8f3',
      background: '#f5f7fa',
      surface: '#ffffff',
      surfaceContainer: '#e9eef4',
      surfaceContainerLow: '#f5f7fa',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#dde5ee',
      onBackground: '#14222f',
      onSurface: '#14222f',
      onSurfaceVariant: '#516273',
      outlineVariant: '#cfd9e3',
      fontHeadline: "'Plus Jakarta Sans', sans-serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontLabel: "'Plus Jakarta Sans', sans-serif",
    },
    categories: [
      { name: 'Estructuras', icon: 'foundation', href: 'estructuras' },
      { name: 'Tuberías y válvulas', icon: 'plumbing', href: 'tuberias' },
      { name: 'Tanques', icon: 'propane_tank', href: 'tanques' },
      { name: 'Soldadura', icon: 'construction', href: 'soldadura' },
    ],
    // Sin precio a propósito: esta plantilla cotiza por WhatsApp.
    demoProducts: [
      { name: 'Estructuras para naves industriales', price: 0, category: 'Estructuras', image: '/sel/nave.jpg', description: 'Fabricación y montaje de estructuras metálicas y coberturas' },
      { name: 'Techos y coberturas metálicas', price: 0, category: 'Estructuras', image: '/sel/techo.jpg', description: 'Armado de tijerales y cobertura para locales y galpones' },
      { name: 'Montaje de tubería y válvulas en planta', price: 0, category: 'Tuberías y válvulas', image: '/sel/planta-gas.jpg', description: 'Instalación en plantas de gas y de procesos' },
      { name: 'Soldeo de tubería', price: 0, category: 'Tuberías y válvulas', image: '/sel/soldador-tuberia.jpg', description: 'Acero al carbono e inoxidable, en diferentes diámetros' },
      { name: 'Fabricación de tanques', price: 0, category: 'Tanques', image: '/sel/tanques.jpg', description: 'En acero inoxidable y al carbono, fabricación y montaje' },
      { name: 'Soldadura en general', price: 0, category: 'Soldadura', image: '/sel/soldadura-hex.jpg', description: 'Trabajos de soldadura a medida, en taller o en obra' },
    ],
    zona: 'Pucallpa - Ucayali',
    direccion: 'Manantay, Pucallpa',
    horario: 'Lunes a Sábado: 8:00 AM – 6:00 PM',
    whatsapp: '51981868116',
  },
  gas: {
    id: 'gas',
    name: 'Distribuidora de Gas',
    category: 'Servicios',
    heroImage: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80',
    heroAlt: 'Cocina con llama de gas encendida',
    theme: {
      primary: '#e8590c',
      onPrimary: '#ffffff',
      primaryContainer: '#b8430a',
      secondary: '#1f3a5f',
      secondaryContainer: '#dbe6f5',
      background: '#f7f9fc',
      surface: '#ffffff',
      surfaceContainer: '#eaeff7',
      surfaceContainerLow: '#f7f9fc',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#dde5f1',
      onBackground: '#13233a',
      onSurface: '#13233a',
      onSurfaceVariant: '#506280',
      outlineVariant: '#cfd9e8',
      fontHeadline: "'Plus Jakarta Sans', sans-serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontLabel: "'Plus Jakarta Sans', sans-serif",
    },
    categories: [
      { name: 'Balones de gas', icon: 'propane_tank', href: 'balones' },
      { name: 'Accesorios', icon: 'build', href: 'accesorios' },
      { name: 'Servicios', icon: 'local_shipping', href: 'servicios' },
    ],
    // Precio 0 a propósito: esta plantilla no muestra precios, el cliente consulta por WhatsApp.
    demoProducts: [
      { name: 'Balón de gas 10 kg', price: 0, category: 'Balones de gas', image: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400&q=80', description: 'Recarga a domicilio, balón sellado y con válvula nueva' },
      { name: 'Balón de gas 15 kg', price: 0, category: 'Balones de gas', image: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400&q=80', description: 'Ideal para hogares y restaurantes pequeños' },
      { name: 'Balón de gas 45 kg', price: 0, category: 'Balones de gas', image: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400&q=80', description: 'Uso industrial y negocios de comida' },
      { name: 'Regulador y manguera', price: 0, category: 'Accesorios', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80', description: 'Con abrazaderas, certificados' },
      { name: 'Instalación y revisión', price: 0, category: 'Servicios', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80', description: 'Revisión de fugas y conexión segura' },
    ],
    zona: 'Pucallpa - Ucayali',
    direccion: 'Av. Centenario 456',
    horario: 'Lunes a Sábado: 7:00 AM – 8:00 PM',
    rating: 4.7,
    whatsapp: '51987654321',
  },
  belleza: {
    id: 'belleza',
    name: 'Salón de Belleza',
    category: 'Moda y Belleza',
    heroImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&q=80',
    heroAlt: 'Salón de belleza con sillón de peluquería y espejos',
    theme: {
      primary: '#c2577a',
      onPrimary: '#ffffff',
      primaryContainer: '#9d3f60',
      secondary: '#3b2433',
      secondaryContainer: '#f6e3ea',
      background: '#fdf7f8',
      surface: '#ffffff',
      surfaceContainer: '#f7eaee',
      surfaceContainerLow: '#fdf7f8',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#f1dde4',
      onBackground: '#2b1a24',
      onSurface: '#2b1a24',
      onSurfaceVariant: '#7a5a68',
      outlineVariant: '#ead3dc',
      fontHeadline: "'Plus Jakarta Sans', sans-serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontLabel: "'Plus Jakarta Sans', sans-serif",
    },
    categories: [
      { name: 'Uñas', icon: 'brush', href: 'unas' },
      { name: 'Cabello', icon: 'content_cut', href: 'cabello' },
      { name: 'Cejas y pestañas', icon: 'visibility', href: 'cejas' },
      { name: 'Productos', icon: 'shopping_bag', href: 'productos' },
    ],
    // Los servicios llevan la duración en subcategory; el cliente los reserva (fecha y hora), no los agrega al carrito.
    demoProducts: [
      { name: 'Manicura en gel', price: 45, category: 'Uñas', subcategory: '60 min', esServicio: true, image: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&q=80', description: 'Esmaltado semipermanente con limado y cuidado de cutículas' },
      { name: 'Pedicura spa', price: 60, category: 'Uñas', subcategory: '75 min', esServicio: true, image: 'https://images.unsplash.com/photo-1610992015732-2449b76344bc?w=400&q=80', description: 'Exfoliación, masaje de pies y esmaltado' },
      { name: 'Corte y peinado', price: 40, category: 'Cabello', subcategory: '45 min', esServicio: true, image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400&q=80', description: 'Corte a tu estilo con lavado y secado' },
      { name: 'Tinte y brillo', price: 120, category: 'Cabello', subcategory: '2 h', esServicio: true, image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&q=80', description: 'Color completo con tratamiento de brillo' },
      { name: 'Diseño de cejas', price: 25, category: 'Cejas y pestañas', subcategory: '30 min', esServicio: true, image: 'https://images.unsplash.com/photo-1522337094846-8a81113521f0?w=400&q=80', description: 'Perfilado y diseño según la forma de tu rostro' },
      { name: 'Aceite de cutículas', price: 18, category: 'Productos', image: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400&q=80', description: 'Nutre y suaviza, con vitamina E' },
    ],
    zona: 'Pucallpa - Ucayali',
    direccion: 'Jr. Tarapacá 321',
    horario: 'Lunes a Sábado: 9:00 AM – 7:00 PM',
    rating: 4.8,
    whatsapp: '51987654321',
  },
  terreno1: {
    id: 'terreno1',
    name: 'Terreno 1',
    category: 'Inmuebles',
    heroImage: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1400&q=80',
    heroAlt: 'Terreno para la venta',
    theme: {
      primary: '#f5a623',
      onPrimary: '#1b2a4a',
      primaryContainer: '#c98410',
      secondary: '#3d4b6b',
      secondaryContainer: '#dde3f2',
      background: '#f6f7fb',
      surface: '#ffffff',
      surfaceContainer: '#eceff6',
      surfaceContainerLow: '#f6f7fb',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#e1e6f1',
      onBackground: '#1b2a4a',
      onSurface: '#1b2a4a',
      onSurfaceVariant: '#5b6785',
      outlineVariant: '#dfe3ee',
      fontHeadline: "'Plus Jakarta Sans', sans-serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontLabel: "'Plus Jakarta Sans', sans-serif",
    },
    categories: [
      { name: 'Yarinacocha', icon: 'landscape', href: 'yarinacocha' },
      { name: 'Callería', icon: 'landscape', href: 'calleria' },
      { name: 'Manantay', icon: 'landscape', href: 'manantay' },
      { name: 'Campo Verde', icon: 'landscape', href: 'campo-verde' },
    ],
    demoProducts: [
      { name: 'Lote 200 m² con título', price: 45000, category: 'Yarinacocha', image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80', description: 'Esquina, agua y luz cerca, a 5 min de la laguna' },
      { name: 'Terreno 10 x 20 m', price: 38000, category: 'Callería', image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80', description: 'Plano, listo para construir' },
      { name: 'Lote 300 m² frente a pista', price: 62000, category: 'Manantay', image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', description: 'Ideal para local comercial' },
      { name: 'Chacra 1 hectárea', price: 90000, category: 'Campo Verde', image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80', description: 'Con acceso por carretera, apta para cultivo' },
    ],
    zona: 'Pucallpa - Ucayali',
    direccion: 'Jr. Ucayali 123',
    horario: '9:00 AM – 6:00 PM',
    rating: 4.7,
    whatsapp: '51987654321',
  },
  terreno2: {
    id: 'terreno2',
    name: 'Terreno 2',
    category: 'Inmuebles',
    heroImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1400&q=80',
    heroAlt: 'Terreno para la venta',
    theme: {
      primary: '#ff6a00',
      onPrimary: '#ffffff',
      primaryContainer: '#c95300',
      secondary: '#5a5240',
      secondaryContainer: '#ebe5d3',
      background: '#f8f6f1',
      surface: '#ffffff',
      surfaceContainer: '#efeadd',
      surfaceContainerLow: '#f8f6f1',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#e6e0d0',
      onBackground: '#2a2418',
      onSurface: '#2a2418',
      onSurfaceVariant: '#6b6250',
      outlineVariant: '#e2ddd0',
      fontHeadline: "'Plus Jakarta Sans', sans-serif",
      fontBody: "'Plus Jakarta Sans', sans-serif",
      fontLabel: "'Plus Jakarta Sans', sans-serif",
    },
    categories: [
      { name: 'Yarinacocha', icon: 'landscape', href: 'yarinacocha' },
      { name: 'Callería', icon: 'landscape', href: 'calleria' },
      { name: 'Manantay', icon: 'landscape', href: 'manantay' },
      { name: 'Campo Verde', icon: 'landscape', href: 'campo-verde' },
    ],
    demoProducts: [
      { name: 'Lote 200 m² con título', price: 45000, category: 'Yarinacocha', image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80', description: 'Esquina, agua y luz cerca, a 5 min de la laguna' },
      { name: 'Terreno 10 x 20 m', price: 38000, category: 'Callería', image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80', description: 'Plano, listo para construir' },
      { name: 'Lote 300 m² frente a pista', price: 62000, category: 'Manantay', image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', description: 'Ideal para local comercial' },
      { name: 'Chacra 1 hectárea', price: 90000, category: 'Campo Verde', image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80', description: 'Con acceso por carretera, apta para cultivo' },
    ],
    zona: 'Pucallpa - Ucayali',
    direccion: 'Jr. Ucayali 123',
    horario: '9:00 AM – 6:00 PM',
    rating: 4.7,
    whatsapp: '51987654321',
  },

  rack: {
    id: 'rack',
    name: 'TechHome Showroom',
    category: 'Hogar y Tecnología',
    heroImage: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=1200&q=80',
    heroAlt: 'modern home entertainment setup with large screen and elegant rack',
    theme: {
      primary: '#c97c3a',
      onPrimary: '#ffffff',
      primaryContainer: '#e8963e',
      secondary: '#a0a0a0',
      secondaryContainer: '#3a3a3a',
      background: '#0f0f0f',
      surface: '#1a1a1a',
      surfaceContainer: '#222222',
      surfaceContainerLow: '#181818',
      surfaceContainerLowest: '#111111',
      surfaceContainerHigh: '#2a2a2a',
      onBackground: '#f0ece6',
      onSurface: '#f0ece6',
      onSurfaceVariant: '#b0a898',
      outlineVariant: '#3a3530',
      fontHeadline: "'Outfit', sans-serif",
      fontBody: "'Outfit', sans-serif",
      fontLabel: "'Outfit', sans-serif",
    },
    categories: [
      { name: 'Racks para TV', icon: 'tv', href: 'racks' },
      { name: 'Soportes de Pared', icon: 'display_settings', href: 'soportes' },
      { name: 'Muebles TV', icon: 'weekend', href: 'muebles' },
      { name: 'Accesorios', icon: 'cable', href: 'accesorios' },
      { name: 'Instalación', icon: 'construction', href: 'instalacion' },
    ],
    demoProducts: [
      { name: 'Rack Flotante 120 cm', price: 189.00, category: 'Racks para TV', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80', description: 'Madera MDF negro mate, soporta hasta 60 kg. Incluye 2 repisas y cableado oculto.' },
      { name: 'Rack Industrial 150 cm', price: 249.00, category: 'Racks para TV', image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&q=80', description: 'Madera maciza + estructura metálica. Para TVs de 55" a 85". Diseño urban loft.' },
      { name: 'Soporte Pared Full Motion', price: 89.00, category: 'Soportes de Pared', image: 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=400&q=80', description: 'Articulado, gira 180°. Compatible con TVs 32"-75". Incluye pernos y nivel.' },
      { name: 'Soporte Fijo Anti-vibración', price: 45.00, category: 'Soportes de Pared', image: 'https://images.unsplash.com/photo-1461151304267-38535e780b79?w=400&q=80', description: 'Ultra delgado 3 cm. Soporta hasta 55 kg. Compatible con VESA 400x400.' },
      { name: 'Mueble TV Esquinero', price: 320.00, category: 'Muebles TV', image: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=400&q=80', description: 'Para esquinas, 3 niveles, con puertas de vidrio. Ideal para salas compactas.' },
      { name: 'Cable HDMI 4K 2m', price: 25.00, category: 'Accesorios', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80', description: 'HDMI 2.1 certificado. 48 Gbps, 4K@120Hz, HDR. Compatible con PS5 y Xbox.' },
      { name: 'Instalación en Pared', price: 80.00, category: 'Instalación', image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&q=80', description: 'Incluye: desmontaje del equipo anterior, montaje del soporte y cableado prolijo.' },
    ],
    zona: 'Lima - Perú',
    direccion: 'Delivery a toda Lima',
    horario: 'Lun – Sáb: 9 AM – 7 PM',
    rating: 4.8,
    whatsapp: '51987654321',
  },
  uniformes: {
    id: 'uniformes',
    name: 'Uniformes Deportivos',
    category: 'Moda',
    heroImage: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=1200&q=80',
    heroAlt: 'jugador con camiseta deportiva en una cancha',
    theme: {
      primary: '#f5c518',
      onPrimary: '#14171f',
      primaryContainer: '#ffd84d',
      secondary: '#8b93a7',
      secondaryContainer: '#232a3d',
      background: '#0b1020',
      surface: '#131a2e',
      surfaceContainer: '#1a2238',
      surfaceContainerLow: '#10172a',
      surfaceContainerLowest: '#0b1020',
      surfaceContainerHigh: '#222b45',
      onBackground: '#f3f5fa',
      onSurface: '#f3f5fa',
      onSurfaceVariant: '#aab2c8',
      outlineVariant: '#2c3550',
      fontHeadline: "'Outfit', sans-serif",
      fontBody: "'Outfit', sans-serif",
      fontLabel: "'Outfit', sans-serif",
    },
    categories: [
      { name: 'Camisetas', icon: 'sports_soccer', href: 'camisetas' },
      { name: 'Conjuntos', icon: 'checkroom', href: 'conjuntos' },
      { name: 'Polos y piqué', icon: 'styler', href: 'polos' },
      { name: 'Buzos y casacas', icon: 'dry_cleaning', href: 'buzos' },
      { name: 'Uniformes escolares', icon: 'school', href: 'escolares' },
      { name: 'Accesorios', icon: 'sports', href: 'accesorios' },
    ],
    demoProducts: [
      { name: 'Camiseta sublimada full color', price: 35.00, category: 'Camisetas', image: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=400&q=80', description: 'Diseño 100 % personalizado con tu escudo, nombre y número. Tela deportiva que respira.' },
      { name: 'Conjunto camiseta + short', price: 55.00, category: 'Conjuntos', image: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=400&q=80', description: 'El uniforme completo para tu equipo. Pedido mínimo por docena, con precio especial por mayor.' },
      { name: 'Polo piqué con bordado', price: 42.00, category: 'Polos y piqué', image: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=400&q=80', description: 'Ideal para colegios, empresas y delegaciones. Bordado de tu logo incluido.' },
      { name: 'Buzo de entrenamiento', price: 80.00, category: 'Buzos y casacas', image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&q=80', description: 'Casaca y pantalón a juego, con tus colores y el nombre del equipo.' },
      { name: 'Uniforme escolar deportivo', price: 48.00, category: 'Uniformes escolares', image: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=400&q=80', description: 'Polo y short para educación física, en todas las tallas de niño y adulto.' },
      { name: 'Medias deportivas (par)', price: 8.00, category: 'Accesorios', image: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400&q=80', description: 'En los colores de tu uniforme. Se piden por docena.' },
    ],
    zona: 'Pucallpa - Ucayali',
    direccion: 'Pedidos por WhatsApp',
    horario: 'Lun – Sáb: 8 AM – 7 PM',
    rating: 4.8,
    whatsapp: '51987654321',
  },

  hogar: {
    id: 'hogar',
    name: 'Hogar y Soportes',
    category: 'Hogar',
    heroImage: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=1200&q=80',
    heroAlt: 'cocina moderna con lavadero y grifería',
    theme: {
      primary: '#0b5ed7',
      onPrimary: '#ffffff',
      primaryContainer: '#2f7bf0',
      secondary: '#5b6b82',
      secondaryContainer: '#dbe6f7',
      background: '#f4f7fb',
      surface: '#ffffff',
      surfaceContainer: '#e9eff8',
      surfaceContainerLow: '#eef3fa',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#dfe7f3',
      onBackground: '#14202e',
      onSurface: '#14202e',
      onSurfaceVariant: '#4d5b70',
      outlineVariant: '#c8d3e3',
      fontHeadline: "'Outfit', sans-serif",
      fontBody: "'Outfit', sans-serif",
      fontLabel: "'Outfit', sans-serif",
    },
    categories: [
      { name: 'Lavaderos', icon: 'countertops', href: 'lavaderos' },
      { name: 'Mesas y estantes', icon: 'table_restaurant', href: 'mesas-y-estantes' },
      { name: 'Soportes', icon: 'construction', href: 'soportes' },
      { name: 'Accesorios', icon: 'plumbing', href: 'accesorios' },
      { name: 'Servicios', icon: 'handyman', href: 'servicios' },
    ],
    demoProducts: [
      { name: 'Lavadero de acero inoxidable', price: 280.00, category: 'Lavaderos', image: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=400&q=80', description: 'Acero inoxidable resistente y duradero, con poza y escurridero. Medidas a pedido.' },
      { name: 'Lavadero de dos pozas', price: 420.00, category: 'Lavaderos', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80', description: 'Dos pozas y escurridero, ideal para cocinas y negocios de comida.' },
      { name: 'Mesa de trabajo de acero', price: 350.00, category: 'Mesas y estantes', image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=400&q=80', description: 'Superficie lisa y fácil de limpiar, con repisa inferior.' },
      { name: 'Soporte metálico reforzado', price: 65.00, category: 'Soportes', image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&q=80', description: 'Soporte de fierro con pintura anticorrosiva, medidas a pedido.' },
      { name: 'Kit de grifería y desagüe', price: 95.00, category: 'Accesorios', image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&q=80', description: 'Todo lo necesario para instalar tu lavadero.' },
      { name: 'Instalación a domicilio', price: 80.00, category: 'Servicios', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80', description: 'Instalación de tu lavadero o soporte en tu casa o negocio.' },
    ],
    zona: 'Pucallpa - Ucayali',
    direccion: 'Pedidos por WhatsApp',
    horario: 'Lun – Sáb: 8 AM – 6 PM',
    rating: 4.8,
    whatsapp: '51987654321',
  },

  helados: {
    id: 'helados',
    name: 'Heladería',
    category: 'Restaurantes',
    heroImage: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=1200&q=80',
    heroAlt: 'conos de helado artesanal con frutas y flores',
    theme: {
      primary: '#e0457b',
      onPrimary: '#ffffff',
      primaryContainer: '#ff7aa8',
      secondary: '#8a6b78',
      secondaryContainer: '#fde3ec',
      background: '#fff8fb',
      surface: '#ffffff',
      surfaceContainer: '#fdebf2',
      surfaceContainerLow: '#fff1f6',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerHigh: '#f9dce8',
      onBackground: '#2b1620',
      onSurface: '#2b1620',
      onSurfaceVariant: '#7a5866',
      outlineVariant: '#efcfdb',
      fontHeadline: "'Outfit', sans-serif",
      fontBody: "'Outfit', sans-serif",
      fontLabel: "'Outfit', sans-serif",
    },
    categories: [
      { name: 'Helados', icon: 'icecream', href: 'helados' },
      { name: 'Copas y sundaes', icon: 'local_bar', href: 'copas' },
      { name: 'Paletas', icon: 'sports_bar', href: 'paletas' },
      { name: 'Malteadas y frappés', icon: 'local_cafe', href: 'malteadas' },
      { name: 'Litros y tortas', icon: 'cake', href: 'litros' },
      { name: 'Extras', icon: 'add_circle', href: 'extras' },
    ],
    demoProducts: [
      { name: 'Cono de dos sabores', price: 6.00, category: 'Helados', image: 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400&q=80', description: 'Elige dos sabores del día en cono de barquillo.' },
      { name: 'Helado de tres bolas', price: 10.00, category: 'Helados', image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=400&q=80', description: 'Tres bolas a elección, en vasito o en cono.' },
      { name: 'Copa brownie y chocolate', price: 16.00, category: 'Copas y sundaes', image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&q=80', description: 'Helado, brownie, galleta y salsa de chocolate.' },
      { name: 'Paleta de fresa con crema', price: 4.00, category: 'Paletas', image: 'https://images.unsplash.com/photo-1560008581-09826d55c0c4?w=400&q=80', description: 'Paleta cremosa con trocitos de fruta.' },
      { name: 'Malteada de fresa', price: 12.00, category: 'Malteadas y frappés', image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=400&q=80', description: 'Con helado, leche y fresas frescas.' },
      { name: 'Litro de helado (2 sabores)', price: 28.00, category: 'Litros y tortas', image: 'https://images.unsplash.com/photo-1567206563064-6f60f40a2b57?w=400&q=80', description: 'Un litro con dos sabores a elección, para compartir.' },
    ],
    zona: 'Pucallpa - Ucayali',
    direccion: 'Pedidos por WhatsApp',
    horario: 'Todos los días: 12 PM – 10 PM',
    rating: 4.8,
    whatsapp: '51987654321',
  },
};

export function getAllTemplates(): TemplateConfig[] {
  return Object.values(TEMPLATES).filter((t) => t.id !== 'default');
}

export function getTemplate(id: string): TemplateConfig | null {
  return TEMPLATES[id] ?? null;
}

export function getDemoProducts(templateId: string): DemoProduct[] {
  const tmpl = TEMPLATES[templateId];
  return tmpl?.demoProducts ?? [];
}
